modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[modproperties.${mod_id}]
dominionsword_addon=true
dominionsword_addon_name_zh_cn="统御之剑：冰火传说兼容"
dominionsword_addon_name_en_us="Dominion Sword: Ice And Fire Compatibility"
dominionsword_addon_name_ja_jp="ドミニオンソード：Ice And Fire 互換"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="dominionsword"
mandatory=true
versionRange="[1.28.1,1.29)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="iceandfire"
mandatory=true
versionRange="[1.2.7,1.2.8)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="uranus"
mandatory=true
versionRange="[2,)"
ordering="NONE"
side="BOTH"
